### ISSUE TITLE
LIN 2.0 Support?

### ISSUE THREAD

**Issue by EliasKotlyar** [lin-bus/linux-lin#12]
Hello dear Developers.

Many thanks for your work. Yesterday i figured out that this project does not happen to have LIN2.0 Support. So maybe include some kernel parameter to have it in the future? At least we can have it written in the description , so people do not get confused

**Comment by ppisa** [comment]
Please, can you report what makes you a problems? The project has been actively developed during 2011 and 2012 years, but we consulted LIN 2.2 specification version. Old 1.0 and new 2.0 version rules for checksum computation are supported.
If the CAN ID controlling LIN mode contains LIN_CHECKSUM_EXTENDED bit set then enhanced checksum computation is used to send message. receive has to match enhanced checksum as well. But when not set then receive tries and accepts both options.

The API does not follow specification, it is integrated to SocketCAN. Automatic baudrate detection in the slave mode is not implemented and hardly possible for the typical target hardware.

So generally, implemented is basic functionality for communication, no low power, wakeup etc... But it should be 2.0 devices and basic use compatible. But if you provide patch or other enhancement for documentation with description of the limitations than it would be great. If you help to implement something even better. I have personally no use for the project from 2014 or 2016 when I have done last paid consultation. We use CAN and cosult CAN and CAN FD for Elektroline.cz and other companies, support GNU/Linux and NuttX there and investing some my spare time to our CTU CAN FD pet.

But from time to time I try to consolidate what is in this LIN project to be usable for others.

Some more current projects works open and with to our students there https://gitlab.fel.cvut.cz/otrees/org/-/wikis/home . CAN related there https://canbus.pages.fel.cvut.cz/ , my company there https://gitlab.com/pikron . The work with students even on the paid contract limited to the work which is fully published and open-source. Most of company as base support or research (even for ESA) open as well. and when touching projects maintained by others, then mainlined if there is value for community.

**Comment by ppisa** [comment]
No repose to description that ssLIN includes LIN 2.0 support and it should be functional. If there is found real compatibility problem, reopen the issue, please.
